name: React Build Action

run-name: Building a react app

on: push
  push: null
  pull_request: null

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install node.js
        uses: actions/setup-node@v1
        with: 
          node-version: 16
- name: Checkout code
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter@v6.3.0  # x-release-please-version
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm install
      - run: npm run build
      - run: npm test